### ISSUE TITLE
Use this package with appium

### ISSUE THREAD

**Issue by xcarpentier** [awslabs/wdio-aws-device-farm-service#6]
Hi,
Thanks for this service.
Is that possible to use it with appium?

**Comment by caglaburcu** [comment]
No it is not.
You need to zip your tests and upload it to Device Farm to work with Appium.
https://docs.aws.amazon.com/devicefarm/latest/developerguide/test-types-appium.html#test-types-appium-prepare
https://aws.amazon.com/blogs/mobile/testing-mobile-apps-across-hundreds-of-real-devices-with-appium-node-js-and-aws-device-farm/

This package only works for Device Farm desktop browser testing.
